on:
    push:
      # Sequence of patterns matched against refs/tags
      tags:
        - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
  
name: Create new Release

jobs:
    build:
        name: Create Release
        runs-on: ubuntu-latest

        steps:

        - name: Checkout code
          uses: actions/checkout@v2
        - name: Invoke Copr hook
          uses: distributor/workflow-webhook@v1
          env:
            webhook_url: ${{ secrets.WEBHOOK_URL }}
        - name: Create Release
          id: create_release
          uses: actions/create_release@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            tag_name: ${{ github.ref }}
            release_name: Release ${{ github.ref }}
            body: |
              Automated release
            draft: false
            prerelease: false
